#!/bin/sh

regex='@gmail\.com$'
email=$GIT_AUTHOR_EMAIL

if [[ $email =~ $regex ]];
then
    echo "your email $email satisfies the git policy"
    exit 0
else
    echo "Your email $email is not authorised to commit to this repository"
    exit 1
fi